name: yolo-flask
channels:
  - defaults
dependencies:
  - python = 3.9
  - pip
  - pip:
    - flask
    - opencv-python
    - pybase64
    - pillow
    - ultralytics
    - deep_sort_realtime
    - shapely